import type { PatchResult } from './patch';

export interface ValidationExportInputs {
  result: PatchResult;
  frequencyHz: number;
  epsilonR: number;
  heightM: number;
  lossTangent: number;
  targetImpedanceOhm: number;
  substrateName: string;
}

/**
 * Generates a filled-in measurement checklist (Markdown) for the currently
 * synthesized design, matching the template in
 * validation/PHYSICAL_BUILD_AND_MEASUREMENT.md — the point is that every
 * predicted number the user needs for fabrication and comparison comes
 * straight out of the app, so there's no step where someone re-types a
 * dimension from the screen into a fab order or a lab notebook and gets a
 * digit wrong.
 */
export function buildValidationPackage(inputs: ValidationExportInputs): string {
  const { result, frequencyHz, epsilonR, heightM, lossTangent, targetImpedanceOhm, substrateName } = inputs;

  const mm = (m: number) => `${(m * 1000).toFixed(4)} mm`;
  const ghz = (hz: number) => `${(hz / 1e9).toFixed(6)} GHz`;

  const feedLine =
    result.insetFeedDepth !== null
      ? `${mm(result.insetFeedDepth)} from the radiating edge, centered along the width`
      : 'UNREACHABLE at this target impedance — see warnings below before fabricating anything';

  return `# OpenRF validation package

Generated from a live design in the OpenRF patch antenna synthesizer. Every number below came
directly from the app — nothing here was hand-transcribed, so treat this file as the source of
truth for fabrication and measurement, not the screen.

## Design target

| Parameter | Value |
|---|---|
| Substrate | ${substrateName} |
| Resonant frequency (target) | ${ghz(frequencyHz)} |
| εr | ${epsilonR} |
| tan δ | ${lossTangent} |
| Substrate height (h) | ${mm(heightM)} |
| Target feed impedance | ${targetImpedanceOhm} Ω |

## Synthesized geometry (fabricate to these dimensions)

| Parameter | Value |
|---|---|
| Patch width (W) | ${mm(result.width)} |
| Patch length (L) | ${mm(result.length)} |
| Feed inset depth (y0) | ${feedLine} |
| Effective εreff | ${result.epsilonReff.toFixed(5)} |
| Ground plane (recommended min.) | ${mm(result.length + 6 * heightM)} × ${mm(result.width + 6 * heightM)} (L+6h × W+6h rule of thumb) |

## Predicted electrical performance (compare your measurement against these)

| Parameter | Predicted |
|---|---|
| Resonant frequency | ${ghz(frequencyHz)} (by construction) |
| Edge resistance (Rin, y=0) | ${result.edgeResistance.toFixed(2)} Ω |
| Radiation Q | ${result.radiationQ.toFixed(2)} |
| Fractional bandwidth (VSWR ≤ 2) | ${(result.fractionalBandwidthVswr2 * 100).toFixed(3)}% (${((result.fractionalBandwidthVswr2 * frequencyHz) / 1e6).toFixed(2)} MHz) |
| Suggested VNA sweep span | ${ghz(frequencyHz - result.fractionalBandwidthVswr2 * frequencyHz * 4)} to ${ghz(frequencyHz + result.fractionalBandwidthVswr2 * frequencyHz * 4)} (±4 predicted bandwidths) |

## Model notes carried over from the synthesis (read before trusting the numbers above)

${result.warnings.map((w) => `- ${w}`).join('\n')}

## Measurement results (fill in after building — see validation/PHYSICAL_BUILD_AND_MEASUREMENT.md)

| Quantity | Predicted | Measured | Δ (%) |
|---|---|---|---|
| Resonant frequency | ${ghz(frequencyHz)} | | |
| −10dB bandwidth | ${((result.fractionalBandwidthVswr2 * frequencyHz) / 1e6).toFixed(2)} MHz | | |
| S11 at resonance (dB) | ≈ 0 (matched by design) | | — |

---
Generated by OpenRF (100% client-side) — https://github.com/ (see project README/spec).
`;
}

export function downloadValidationPackage(inputs: ValidationExportInputs): void {
  const markdown = buildValidationPackage(inputs);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const freqLabel = (inputs.frequencyHz / 1e9).toFixed(2).replace('.', 'p');
  a.href = url;
  a.download = `openrf-validation-${freqLabel}GHz.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
